version: "3.6"
services:
  redis:
    container_name: redis
    image: redis:6.0.8-alpine
    ports:
      - "6379:6379"
  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

  woofer-api:
    container_name: backend
    build: .
    volumes:
      - ./:/srv/woofer-api
      - woofer-api_node_modules:/srv/woofer-api/node_modules
    command: npm run dev
    ports:
      - "${PORT}:${PORT}"
volumes:
  woofer-api_node_modules:
